---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-acmpca-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - acmpca.services.k8s.aws
  resources:
  - certificates
  - certificateauthorities
  - certificateauthorityactivations
  verbs:
  - get
  - list
  - watch
