apiVersion: acmpca.services.k8s.aws/v1alpha1
kind: CertificateAuthorityActivation
metadata:
  name: <CA ACTIVATION NAME>
spec:
  certificateAuthorityRef:
    from:
      name: <CA NAME>
  certificate:
    namespace: default
    name: certificate-secret
    key: certificate
  status: ACTIVE