apiVersion: v1
kind: Secret
metadata:
  name: end-entity-secret
  namespace: default
data:
  certificate: ""
---
apiVersion: acmpca.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: end-entity-certificate
  annotations:
    acmpca.services.k8s.aws/certificate-secret-namespace: default
    acmpca.services.k8s.aws/certificate-secret-name: end-entity-secret
    acmpca.services.k8s.aws/certificate-secret-key: certificate
spec:
  certificateAuthorityRef:
    from:
      name: sub-ca
  certificateSigningRequest: <CSR>
  signingAlgorithm: SHA256WITHRSA
  validity:
    type: DAYS
    value: 70