apiVersion: v1
kind: Secret
metadata:
  name: root-ca-certificate-secret
  namespace: default
data:
  certificate: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: root-ca-certificate-chain-secret
  namespace: default
data:
  certificateChain: ""
---
apiVersion: acmpca.services.k8s.aws/v1alpha1
kind: CertificateAuthority
metadata:
  name: root-ca
spec:
  type: ROOT
  certificateAuthorityConfiguration:
    keyAlgorithm: RSA_2048
    signingAlgorithm: SHA256WITHRSA
    subject:
      country: US
      organization: string
      organizationalUnit: string
      distinguishedNameQualifier: string
      state: string
      commonName: root
      serialNumber: string
      locality: string
      title: string
      surname: string
      givenName: string
      initials: DG
      pseudonym: string
      generationQualifier: DBG
  tags:
    - key: tag
      value: val
---
apiVersion: acmpca.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: root-ca-certificate
  annotations:
    acmpca.services.k8s.aws/certificate-secret-namespace: default
    acmpca.services.k8s.aws/certificate-secret-name: root-ca-certificate-secret
    acmpca.services.k8s.aws/certificate-secret-key: certificate
spec:
  certificateAuthorityRef:
    from:
      name: root-ca
  certificateSigningRequestRef:
    from:
      name: root-ca
  signingAlgorithm: SHA256WITHRSA
  templateARN: arn:aws:acm-pca:::template/RootCACertificate/V1
  validity:
    type: DAYS
    value: 100
---
apiVersion: acmpca.services.k8s.aws/v1alpha1
kind: CertificateAuthorityActivation
metadata:
  name: root-ca-activation
  annotations:
    acmpca.services.k8s.aws/chain-secret-namespace: default
    acmpca.services.k8s.aws/chain-secret-name: root-ca-certificate-chain-secret
    acmpca.services.k8s.aws/chain-secret-key: certificateChain
spec:
  certificateAuthorityRef:
    from:
      name: root-ca
  certificate:
    namespace: default
    name: root-ca-certificate-secret
    key: certificate
  status: ACTIVE
