apiVersion: v1
kind: Secret
metadata:
  name: sub-ca-certificate-secret
  namespace: default
data:
  certificate: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: sub-ca-certificate-chain-secret
  namespace: default
data:
  certificateChain: ""
---
apiVersion: acmpca.services.k8s.aws/v1alpha1
kind: CertificateAuthority
metadata:
  name: sub-ca
spec:
  type: SUBORDINATE
  certificateAuthorityConfiguration:
    keyAlgorithm: RSA_2048
    signingAlgorithm: SHA256WITHRSA
    subject:
      country: US
      organization: string
      organizationalUnit: string
      distinguishedNameQualifier: string
      state: string
      commonName: Sub1
      serialNumber: string
      locality: string
      title: string
      surname: string
      givenName: string
      initials: DG
      pseudonym: string
      generationQualifier: DBG
  revocationConfiguration:
    crlConfiguration:
      enabled: False
    ocspConfiguration:
      enabled: False
---
apiVersion: acmpca.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: sub-ca-certificate
  annotations:
    acmpca.services.k8s.aws/certificate-secret-namespace: default
    acmpca.services.k8s.aws/certificate-secret-name: sub-ca-certificate-secret
    acmpca.services.k8s.aws/certificate-secret-key: certificate
spec:
  certificateAuthorityRef:
    from:
      name: root-ca
  certificateSigningRequestRef:
    from:
      name: sub-ca
  signingAlgorithm: SHA256WITHRSA
  templateARN: arn:aws:acm-pca:::template/SubordinateCACertificate_PathLen3/V1
  validity:
    type: DAYS
    value: 90
---
apiVersion: acmpca.services.k8s.aws/v1alpha1
kind: CertificateAuthorityActivation
metadata:
  name: sub-ca-activation
  annotations:
    acmpca.services.k8s.aws/chain-secret-namespace: default
    acmpca.services.k8s.aws/chain-secret-name: sub-ca-certificate-chain-secret
    acmpca.services.k8s.aws/chain-secret-key: certificateChain
spec:
  certificateAuthorityRef:
    from:
      name: sub-ca
  certificate:
    namespace: default
    name: sub-ca-certificate-secret
    key: certificate
  certificateChain:
    namespace: default
    name: root-ca-certificate-secret
    key: certificate
  status: ACTIVE