apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/acmpca.services.k8s.aws_certificates.yaml
  - bases/acmpca.services.k8s.aws_certificateauthorities.yaml
  - bases/acmpca.services.k8s.aws_certificateauthorityactivations.yaml
